### ISSUE TITLE
Compatibility with newest versiones

### ISSUE THREAD

**Issue by CalzaFino** [breezefront/module-breeze-magefan-blog#2]
This module was released about 2 years ago and has not been updated. Is it still compatible with the newest version as of today Feb 24, 2024?

I am experiencing strange behaviors like not displaying correctly inserted products in the blog in the front store and on the admin when I try to edit a Text element it opens the HTML code instead of the text editor as on the Magefan demo pages.

**Comment by CalzaFino** [comment]
I am sorry I saw it was updated a couple of weeks ago but I am still having the mentioned issues. I am not sure if I am running the newest version. I run `composer update swissup/module-breeze-magefan-blog` I the result is `Nothing to install, update or remove`

**Comment by vovayatsyuk** [comment]
> not displaying correctly inserted products in the blog in the front store

Can you please describe how to do that?

> it opens the HTML code instead of the text editor

We do not change the backend so it's not related to Breeze.

**Comment by vovayatsyuk** [comment]
I've fixed css issue with the product widget in the latest update. Does it look ok now?
